require "user.options"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.common-plugin-setup"
require "user.lsp"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.gitsigns"
require "user.neo-tree"
require "user.bufferline"
require "user.lualine"
require "user.fterm"
require "user.project"
require "user.impatient"
require "user.indentline"
require "user.alpha"
require "user.whichkey"
require "user.autocommands"
require "user.lightbulb"
require "user.goto-file"
require "user.rust-tools"
require "user.spectre"
require "user.keymaps"
require "user.dap"
require "user.custom-command"
require "user.barbar"
require "user.telescope"
require "user.snip"




